name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Node Modules
      run: yarn
    - name: Test Library
      run: yarn test
    - name: Build library
      run: yarn build