export { default as Layout } from './layout'
export { default as Map } from './map'
export { default as Home } from './home'
export { default as Detail } from './detail'
export { default as Search } from './search'